#!/bin/sh
### BEGIN INIT INFO
# Provides:          xlshd
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: xlshd login daemon
# Description:       xlshd login daemon
### END INIT INFO

case "$1" in
	start)
		/usr/local/sbin/xlshd
		# forks
		;;
	stop)
		killall xlshd
		;;
	reload|force-reload|restart)
		$0 stop
		$0 start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}" >&2
		exit 2
		;;
esac
